### ISSUE TITLE
Unexpected end of JSON input error

### ISSUE THREAD

**Issue by eyeofastarte** [waffpi/obfuscit#1]
Using an empty starter SevlteKit project and tailwind install after importing and adding to the svelte.config.js preprocess the build presses fail
```
error when starting dev server:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Obfuscate (file:///C:/xampp/htdocs/Votal-deploy-test/node_modules/tailwind-obfuscator/src/twObfuscator.js:19:29)
    at file:///C:/xampp/htdocs/Votal-deploy-test/svelte.config.js?ts=1697018638492:13:3
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```
I ran `npx tailwindcss -i src/app.css -o build/_app/immutable/assets` but got an error
```
[Error: EISDIR: illegal operation on a directory, open 'C:\xampp\htdocs\Votal-deploy-test\build\_app\immutable\assets'] {
  errno: -4068,
  code: 'EISDIR',
  syscall: 'open',
  path: 'C:\\xampp\\htdocs\\Votal-deploy-test\\build\\_app\\immutable\\assets'
}
```
Also, I ran `npx twobfus --tw src/app.css` but nothing happened. I don't know if I have done the setup incorrectly.

Empty project Example: https://github.com/nickt28/Votal-deploy-test

**Comment by ingenful** [comment]
The -o flag with the npx tailwindcss command is indeed for specifying the output CSS file, not the path to the built CSS file. So, you should point it to the exact output file you want, not a directory. 

Just to make it super clear, here's how you can tackle this issue.

`npx tailwindcss -i src/app.css -o build/_app/immutable/assets/app.css --minify`

and then run

`npx twobfus --tw build/_app/immutable/assets/app.css`

**Comment by eyeofastarte** [comment]
Nothing is still happening when I run `npx twobfus --tw build/_app/immutable/assets/app.css`

Also if I run with administrator privilege I get an error instead. My system is Windows which might be an issue.
![image](https://github.com/xinnypie/tailwind-obfuscator/assets/93458816/67f739f7-4cfd-478b-985a-699410e6c2e3)

**Comment by ingenful** [comment]
Hmm, I can confirm that I've tested this on Windows as well, and it worked perfectly fine for me.

You may follow the step.

1. Open CMD and Run as administrator.
2. Type the following commands.

```
regsvr32 jscript.dll     
regsvr32 vbscript.dll
```

Happy coding! If you run into any further issues or have questions, feel free to ask. We're here to help. 😄
